#!/bin/bash

branch="$(git branch --show-current)"

die () {
    echo -e "\033[1;31m${1}\033[0m"
    exit 1
}

case "${branch}" in
    (main|master) die "On branch ${branch}, which is protected." ;;
    *) exit 0 ;;
esac
